server:
  port: 8090

spring:
  datasource:
    url: 'jdbc:h2:mem:house_bd;DB_CLOSE_ON_EXIT=FALSE'
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

